### ISSUE TITLE
Error install plugin : LibreNMS\ComposerHelper::preUpdate

### ISSUE THREAD

**Issue by lynch4fr** [dmbokhan/vlans-compare#3]
Hello,
When I try to install the plugin with the command: ./lnms plugin:add dmbokhan/vlans-compare
I get the error message :

> LibreNMS\ComposerHelper::preUpdate
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
     -Root composer.json requires dmbokhan/vlans-compare * -> satisfiable by dmbokhan/vlans-compare[1.0.0, 1.0.1, 1.0.2, 1.0.3].
     -dmbokhan/vlans-compare[1.0.0, ..., 1.0.3] require librenms/librenms ^23.9.1 -> satisfiable by librenms/librenms[23.9.1, 23.10.0, 23.11.0] from composer repo (https://repo.packagist.org) but librenms/librenms is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require dmbokhan/vlans-compare:*" to figure out if any version is installable, or "composer require dmbokhan/vlans-compare:^2.1" if you know which you need.
Installation failed, reverting ./composer.json and ./composer.lock to their original _content.

I can't find a solution, I think I'm missing a package dependency?
Thanks for your help

**Comment by dmbokhan** [comment]
Hi!

There was librenms/librenms requirement in composer.json, so it couldn't be installed on LibreNMS with daily updates. I didn't see that error because I tested the plugin only on latest stable release (monthly updates). Try to install the plugin again please.

**Comment by lynch4fr** [comment]
Hello,
Thank you, the installation was successful with your help :)

I have access to "Overview - Plugins - Vlans Compare" but when I select 2 devices + click on Compare, I have nothing displayed on the right in Result ? _For your information, I'm comparing 2 identical switches with active-passive redundancy_
Could you help me ? Thanks again

Sincerely

**Comment by dmbokhan** [comment]
The reason of the plugin is to show the difference between created vlans on devices or allowed vlans between ports, so if there no difference between devices vlans lists you should see rows with hostname of chosen devices on green background in Result. Just make sure that LibreNMS collects vlans data and show it on the device's vlan page.

Can you share a screenshot how does it look after you click on Compare button please?

**Comment by lynch4fr** [comment]
I do have Vlan and Port Librenms data on the 2 switches. Here's a screenshot of my display. I've added a screenshot Overview->Plungins->Plugin admin-> Vlans-compare (Settings)
![Capture d’écran de 2023-11-27 09-43-15](https://github.com/dmbokhan/vlans-compare/assets/27801633/bd6819ae-5f6b-4e77-938c-1a7074581fdf)
![Capture d’écran de 2023-11-27 12-13-58](https://github.com/dmbokhan/vlans-compare/assets/27801633/f389e69a-69a9-41b6-ad59-f4f50d047314)

**Comment by dmbokhan** [comment]
Settings page is correct, cuz there is no settings in the plugin.

But something wrong with Result. Can you please open developer tools in your browser and check POST request-response in Network section when you click on Compare button and share it with me.

**Comment by lynch4fr** [comment]
Thanks, I used the developer tools in my browser and was able to correct the error myself. It was a JS compare.js error.

I made a ./lnms plugin:**remove** dmbokhan/vlans-compare and redid the whole plugin installation as in your documentation.

It's great! And your plugin is excellent.
Thanks a lot!
